version: '3.8'
services:
  signicert:
    build: .
    restart: always
    ports:
    - "3002:3002"
    # - 9229:9229
    environment:
      HOSTING_DOMAIN: 'http://localhost:3002'
      PORT: 3002
      SERVER_PRIVATE_KEY: '95219e536fc9c3cb54594996d7e3e343bf503598f7bedced738642b73c63f392' # TODO (developer): Use YOUR OWN key. DO NOT leave the default one.
      CERTIFICATE_TYPE_ID: 'z40BOInXkI8m7f/wBrv4MJ09bZfzZbTj2fJqCtONqCY='
      NODE_ENV: development
      WALLET_STORAGE_URL: 'https://staging-dojo.babbage.systems'
      ROUTING_PREFIX: ''
      SIGNIA_DB_CONNECTION: 'mongodb+srv://signia-serverless:FMiuR3xgDEkKSxml@signia-serverless.be2miu7.mongodb.net/?retryWrites=true&w=majority' # TODO: REMOVE BEFORE COMMITING!
      PERSONA_TOKEN: 'persona_sandbox_d6c26d80-63c8-4ade-b094-4270fcaee9b4'
      NANOSTORE_URL: 'https://staging-nanostore.babbage.systems'
  
  ## Backend database
  # signicert-mysql:
  #   image: "mysql:8.0"
  #   platform: linux/x86_64
  #   hostname: 'signicert-mysql'
  #   command: 'mysqld --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync'
  #   restart: always
  #   volumes:
  #    - './data/signicert-mysql-data:/var/lib/mysql'
  #   environment:
  #     MYSQL_HOST: "127.0.0.1"
  #     MYSQL_TCP_PORT: 3001
  #     MYSQL_ROOT_PASSWORD: "test"
  #     MYSQL_DATABASE: "signicert"
  #   ports:
  #     - "3001:3001"
  #     - "9229:9229"
  #   healthcheck:
  #     test: ["CMD-SHELL", 'mysqladmin ping']
  #     interval: 10s
  #     timeout: 2s
  #     retries: 10