// Phoneverification Certificate Type Definition // TODO: FIX DOCUMENTATION
//
// An Authrite Certifier defines one or more certificate types that they issue and manage.
// The certificate type encompasses a list of fields and their expected and valid values.
// A certificate type is assigned a unique identifier which must be a random 32 byte value
// encoded as a base64 string.
// A new certificate type identifier can be generated by the following code:
//      require('crypto').randomBytes(32).toString('base64')
//
// Do not re-use type identifiers. The value is not private, so we keep it here with the
// certificate structure definition.
//
// The purpose of this certificate is to server as a self-certified external identity to
// be associated with the certificate owner.
export const certificateType = 'vdDWvftf1H+5+ZprUw123kjHlywH+v20aPQTuXgMpNc='
const certificateDefinition = {
  userName: 'John Doe',
  profilePhoto: 'https://pbs.twimg.com/profile_images/1777441236829491200/JWd4tvYB_normal.jpg'
}
const certificateFields = Object.keys(certificateDefinition)

export const xcert: { certificateType: string, certificateDefinition: Record<string, string>, certificateFields: string[] } = {
  certificateType,
  certificateDefinition,
  certificateFields
}

