apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: socialcert-backend-tls
  labels:
    app.kubernetes.io/name: socialcert-backend
    app.kubernetes.io/component: tls
spec:
  secretName: socialcert-backend-tls
  dnsNames: []
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-nginx
