name: Deployment
on:
  push:
    branches:
      - master
      - production
env:
  CURRENT_BRANCH: ${{ github.ref_name =='production' && 'production' || 'master' }}
  GCR_HOST: us.gcr.io
  GOOGLE_PROJECT_ID: computing-with-integrity
  GCR_IMAGE_NAME: socialcert-backend
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         ref: ${{ env.CURRENT_BRANCH }}
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.DOCKER_REGISTRY_PUSH_KEY }}
          registry: ${{ env.GCR_HOST }}
          project_id: ${{ env.GOOGLE_PROJECT_ID }}
          image_name: ${{ env.GCR_IMAGE_NAME }}
          image_tag: ${{ env.CURRENT_BRANCH }}-${{ github.sha }}
      - name: "Create service description file"
        run: "./scripts/mkenv.sh service.${{ env.CURRENT_BRANCH }}.yaml"
        env:
          IMAGE: "${{ env.GCR_HOST }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.GCR_IMAGE_NAME }}:${{ env.CURRENT_BRANCH }}-${{ github.sha }}"
          SERVICE: ${{ env.CURRENT_BRANCH =='production' && 'prod-socialcert-backend' || 'staging-socialcert-backend' }}
          NODE_ENV: ${{ env.CURRENT_BRANCH == 'production' && 'production' || 'staging' }}
          SERVER_PRIVATE_KEY: ${{ env.CURRENT_BRANCH == 'production' && secrets.PROD_SERVER_PRIVATE_KEY || secrets.STAGING_SERVER_PRIVATE_KEY }}
          HOSTING_DOMAIN: ${{ env.CURRENT_BRANCH == 'production' && secrets.PROD_HOSTING_DOMAIN || secrets.STAGING_HOSTING_DOMAIN }}
          DOJO_URL: ${{ env.CURRENT_BRANCH == 'production' && secrets.PROD_DOJO_URL || secrets.STAGING_DOJO_URL }}
          ROUTING_PREFIX: ''
          CERTIFICATE_TYPE_ID: ${{ secrets.CERTIFICATE_TYPE_ID  }}
          SIGNIA_DB_CONNECTION: ${{ env.CURRENT_BRANCH == 'production' && secrets.PROD_SIGNIA_DB_CONNECTION || secrets.STAGING_SIGNIA_DB_CONNECTION }}
          DISCORD_API_ENDPOINT:  ${{ secrets.DISCORD_API_ENDPOINT }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          REDIRECT_URI: ${{ env.CURRENT_BRANCH == 'production' && secrets.PROD_REDIRECT_URI || secrets.STAGING_REDIRECT_URI }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_SERVICE_SID: ${{ secrets.TWILIO_SERVICE_SID }}
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_deploy_creds }}
      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          metadata: "service.${{ env.CURRENT_BRANCH }}.yaml"